Module modHtml

    Public Function GetPoligonoMapa() As String

        Dim html As String = String.Empty

        html = html & "<!DOCTYPE html>"
        html = html & "<html>"
        html = html & "<head>"
        html = html & "<title>Simple Map</title>"
        html = html & "<meta name='viewport' content='initial-scale=1.0'>"
        html = html & "<meta http-equiv='X-UA-Compatible' content='IE=edge'>"
        html = html & "<meta charset='utf-8'>"
        html = html & "<style>"
        html = html & "html, body {"
        html = html & "height: 100%;"
        html = html & "margin: 0;"
        html = html & "padding: 0;"
        html = html & "}"
        html = html & "#map {"
        html = html & "height: 100%;"
        html = html & "}"
        html = html & "</style>"
        html = html & "</head>"
        html = html & "<body>"
        html = html & "<div id='map'></div>"
        html = html & "<input type='hidden' id='txtCoordenadas' name='Coordenadas' value='@@Coordenadas'>"
        html = html & "<input type='hidden' id='txtLatitud' name='Latitud' value='@@Latitud'>"
        html = html & "<input type='hidden' id='txtLongitud' name='Longitud' value='@@Longitud'>"
        html = html & "<script>"
        html = html & "var map;"
        html = html & "var principalPolygon;"
        html = html & "function initMap() {"
        html = html & "var latCenter = document.getElementById('txtLatitud').value;"
        html = html & "var longCenter = document.getElementById('txtLongitud').value;"
        html = html & "var strPolygon = document.getElementById('txtCoordenadas').value;"
        html = html & "map = new google.maps.Map(document.getElementById('map'), {"
        html = html & "zoom: 8,"
        html = html & "center: { lat: -34.654744, lng: -58.555602 },"
        html = html & "mapTypeId: google.maps.MapTypeId.TERRAIN"
        html = html & "});"
        html = html & "var triangleCoords = ["
        html = html & "{ lat: 25.774, lng: -80.190 },"
        html = html & "{ lat: 18.466, lng: -66.118 },"
        html = html & "{ lat: 32.321, lng: -64.757 },"
        html = html & "];"
        html = html & "principalPolygon = new google.maps.Polygon({"
        html = html & "paths: triangleCoords,"
        html = html & "strokeColor: '#FF0000',"
        html = html & "strokeOpacity: 0.8,"
        html = html & "strokeWeight: 2,"
        html = html & "fillColor: '#FF0000',"
        html = html & "fillOpacity: 0.35,"
        html = html & "editable: true,"
        html = html & "draggable: true"
        html = html & "});"
        html = html & "principalPolygon.setMap(map);"
        html = html & "principalPolygon.setMap(null);"
        html = html & "var polygon = strPolygon.split('@');"
        html = html & "var paths = [];"
        html = html & "for (var i = 0; i < polygon.length - 1; i++) {"
        html = html & "var coords = polygon[i].split(';');"
        html = html & "var vert = { lat: parseFloat(coords[0]), lng: parseFloat(coords[1]) };"
        html = html & "paths.push(vert);"
        html = html & "}"
        html = html & "map.setCenter(new google.maps.LatLng(parseFloat(latCenter), parseFloat(longCenter)));"
        html = html & "map.setZoom(parseFloat(8));"
        html = html & "principalPolygon.setPath(paths);"
        html = html & "principalPolygon.setMap(map);"
        html = html & "}"
        html = html & "</script>"
        html = html & "<script src='https://maps.googleapis.com/maps/api/js?key=AIzaSyCgGOZyoyPNYnpqnmUR4NbLsRDowF-sYG8&sensor=false&callback=initMap'>"
        html = html & "</script>"
        html = html & "<script>"
        html = html & "function savePolygon() {"
        html = html & "var polygon = [];"
        html = html & "var vertices = principalPolygon.getPath();"
        html = html & "var strCoords = '';"
        html = html & "for (var i = 0; i < vertices.getLength() ; i++) {"
        html = html & "var xy = vertices.getAt(i);"
        html = html & "strCoords = strCoords + xy.lat() + ';' + xy.lng() + '@';"
        html = html & "}"
        html = html & "return strCoords.substring(0, strCoords.length - 1);"
        html = html & "}"
        html = html & "</script>"
        html = html & "</body>"
        html = html & "</html>"

        Return html

    End Function
    Public Function GetMarcadorMapa() As String
        Dim html As String = String.Empty


        html = html & "<!DOCTYPE html>"
        html = html & "<html>"
        html = html & "<head>"
        html = html & "<title>Visualizador de puntos</title>"
        html = html & "<meta name='viewport' content='initial-scale=1.0'>"
        html = html & "<meta http-equiv='X-UA-Compatible' content='IE=edge'>"
        html = html & "<meta charset='utf-8'>"
        html = html & "<style>"
        html = html & "html,"
        html = html & "body {"
        html = html & "height: 100%;"
        html = html & "margin: 0;"
        html = html & "padding: 0;"
        html = html & "}"
        html = html & "#map {"
        html = html & "height: 100%;"
        html = html & "}"
        html = html & "</style>"
        html = html & "</head>"
        html = html & "<body>"
        html = html & "<div id='map'></div>"
        html = html & "<input type='hidden' id='txtCoordenadas' name='Coordenadas' value='@@Coordenadas'>"
        html = html & "<script>"
        html = html & "var map;"
        html = html & "var principalPolygon;"
        html = html & "function initMap() {"
        html = html & "map = new google.maps.Map(document.getElementById('map'), {"
        html = html & "zoom: 5,"
        html = html & "center: { lat: -34.654744, lng: -58.555602 },"
        html = html & "mapTypeId: google.maps.MapTypeId.TERRAIN"
        html = html & "});"
        html = html & "setMarkers();"
        html = html & "}"
        html = html & "function setMarkers() {"
        html = html & "var strPolygon = document.getElementById('txtCoordenadas').value;"
        html = html & "var makers = strPolygon.split('@');"
        html = html & "var paths = [];"
        html = html & "for (var i = 0; i < makers.length - 1; i++) {"
        html = html & "var coords = makers[i].split(';');"
        html = html & "var position = new google.maps.LatLng(parseFloat(coords[0]), parseFloat(coords[1]));"
        html = html & "if (coords[2] == 1) {"
        html = html & "var marker = new google.maps.Marker({"
        html = html & "position: position,"
        html = html & "title: '',"
        html = html & "icon: 'http://maps.google.com/mapfiles/ms/icons/blue-dot.png'"
        html = html & "});"
        html = html & "}"
        html = html & "else {"
        html = html & "var marker = new google.maps.Marker({"
        html = html & "position: position,"
        html = html & "title: '',"
        html = html & "icon: 'http://maps.google.com/mapfiles/ms/icons/red-dot.png'"
        html = html & "});"
        html = html & "}"
        html = html & "marker.setMap(map);"
        html = html & "}"
        html = html & "}"
        html = html & "</script>"
        html = html & "<script src='https://maps.googleapis.com/maps/api/js?key=AIzaSyCgGOZyoyPNYnpqnmUR4NbLsRDowF-sYG8&&sensor=false&callback=initMap'></script>"
        html = html & "</body>"
        html = html & "</html>"


        Return html


    End Function

End Module
